export const GET_COUNTRY = 'GET_COUNTRY';
export const COUNTRY_RECEIVED = 'COUNTRY_RECEIVED';
export const COUNTRY_REQUEST_FAILED = 'COUNTRY_REQUEST_FAILED';

export const UPDATE_COUNTRY = 'UPDATE_COUNTRY';
export const UPDATE_COUNTRY_SUCCESS = 'UPDATE_COUNTRY_SUCCESS';
export const UPDATE_COUNTRY_FAILED = 'UPDATE_COUNTRY_FAILED';

export const CREATE_COUNTRY = 'CREATE_COUNTRY';
export const CREATE_COUNTRY_SUCCESS = 'CREATE_COUNTRY_SUCCESS';
export const CREATE_COUNTRY_FAILED = 'CREATE_COUNTRY_FAILED';

export const DELETE_COUNTRY = 'DELETE_COUNTRY';
export const DELETE_COUNTRY_SUCCESS = 'DELETE_COUNTRY_SUCCESS';
export const DELETE_COUNTRY_FAILED = 'DELETE_COUNTRY_FAILED';